import { DeliveryReceipt } from '../schema/schema';

export const DELIVERY_RECEIPT_DATA_VERSION = '1.0';

export const DELIVERY_RECEIPTS = [
    {
        id: 'DR-2024-001',
        receipt_number: 'RCP-2024-001',
        supplier_id: 'SUP-001',
        supplier_name: 'Tech Solutions Inc.',
        supplier_tin: '123-456-789-000',
        department_id: 'DEPT-001',
        department_name: 'IT Department',
        delivery_date: new Date('2024-03-01'),
        supporting_documents: ['doc1.pdf', 'doc2.pdf'],
        total_amount: 50000,
        notes: 'First quarter IT supplies',
        status: 'unverified',
        purchase_order: 'PO-2024-001',
        stocked: false,
        receipt_files: [],
        created_at: new Date('2024-03-01'),
        updated_at: new Date('2024-03-01'),
        vatType: 'vat' // Add this line
    },
    {
        id: 'DR-2024-002',
        receipt_number: 'RCP-2024-002',
        supplier_id: 'SUP-002',
        supplier_name: 'Office Depot',
        supplier_tin: '234-567-890-001',
        department_id: 'DEPT-002',
        department_name: 'HR Department',
        delivery_date: new Date('2024-03-05'),
        supporting_documents: ['doc3.pdf'],
        total_amount: 25000,
        notes: 'Office supplies delivery',
        status: 'processing',
        purchase_order: 'PO-2024-002',
        stocked: false,
        receipt_files: [],
        created_at: new Date('2024-03-05'),
        updated_at: new Date('2024-03-05'),
        vatType: 'non-vat' // Add this line
    },
    {
        id: 'DR-2024-003',
        receipt_number: 'RCP-2024-003',
        supplier_id: 'SUP-003',
        supplier_name: 'Furniture Plus',
        supplier_tin: '345-678-901-002',
        department_id: 'DEPT-003',
        department_name: 'Admin Department',
        delivery_date: new Date('2024-03-10'),
        supporting_documents: ['doc4.pdf', 'doc5.pdf'],
        total_amount: 75000,
        notes: 'Office furniture delivery',
        status: 'verified',
        purchase_order: 'PO-2024-003',
        stocked: true,
        receipt_files: [],
        created_at: new Date('2024-03-10'),
        updated_at: new Date('2024-03-10'),
        vatType: 'vat' // Add this line
    },
    {
        id: 'DR-2024-004',
        receipt_number: 'RCP-2024-004',
        supplier_id: 'SUP-004',
        supplier_name: 'Equipment Co.',
        supplier_tin: '456-789-012-003',
        department_id: 'DEPT-004',
        department_name: 'Operations',
        delivery_date: new Date('2024-03-15'),
        supporting_documents: ['doc6.pdf'],
        total_amount: 100000,
        notes: 'Heavy equipment delivery',
        status: 'completed',
        purchase_order: 'PO-2024-004',
        stocked: true,
        receipt_files: [],
        created_at: new Date('2024-03-15'),
        updated_at: new Date('2024-03-15'),
        vatType: 'vat' // Add this line
    },
    {
        id: 'DR-2024-005',
        receipt_number: 'RCP-2024-005',
        supplier_id: 'SUP-005',
        supplier_name: 'Supply Masters',
        supplier_tin: '567-890-123-004',
        department_id: 'DEPT-005',
        department_name: 'Logistics',
        delivery_date: new Date('2024-03-20'),
        supporting_documents: ['doc7.pdf', 'doc8.pdf'],
        total_amount: 30000,
        notes: 'General supplies delivery',
        status: 'unverified',
        purchase_order: 'PO-2024-005',
        stocked: false,
        receipt_files: [],
        created_at: new Date('2024-03-20'),
        updated_at: new Date('2024-03-20'),
        vatType: 'non-vat' // Add this line
    }
];